import type { Metadata } from 'next';
import { Inter } from 'next/font/google'
import { Provider } from 'react-redux';
import { configureStore } from '@reduxjs/toolkit';
import cartReducer from "./State";
import './globals.css';
import React from 'react';
const inter = Inter({ subsets: ['latin'] })

const store = configureStore({
  reducer: {
      cart: cartReducer,
  }
})

type ReduxProviderProps = {
  children: React.ReactNode;
}

function ReduxProvider({children}: ReduxProviderProps){
  return <Provider store={store} >{children}</Provider>
}

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

return (
    <html lang="en"> 
      <ReduxProvider>
        <body className={inter.className}>{children}</body>   
      </ReduxProvider>
    </html>
  )
}


